[build]
publish = "." 
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=*, nfc=*"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
